#!/bin/bash
runspec --config=gcc41.cfg --action=build --tune=base perlbench
runspec --config=gcc41.cfg --action=build --tune=base bzip2
runspec --config=gcc41.cfg --action=build --tune=base gcc
runspec --config=gcc41.cfg --action=build --tune=base bwaves
runspec --config=gcc41.cfg --action=build --tune=base gamess
runspec --config=gcc41.cfg --action=build --tune=base mcf
runspec --config=gcc41.cfg --action=build --tune=base milc
runspec --config=gcc41.cfg --action=build --tune=base zeusmp
runspec --config=gcc41.cfg --action=build --tune=base gromacs
runspec --config=gcc41.cfg --action=build --tune=base cactusADM
runspec --config=gcc41.cfg --action=build --tune=base leslie3d
runspec --config=gcc41.cfg --action=build --tune=base namd
runspec --config=gcc41.cfg --action=build --tune=base gobmk
runspec --config=gcc41.cfg --action=build --tune=base dealII
runspec --config=gcc41.cfg --action=build --tune=base soplex
runspec --config=gcc41.cfg --action=build --tune=base povray
runspec --config=gcc41.cfg --action=build --tune=base calculix
runspec --config=gcc41.cfg --action=build --tune=base hmmer
runspec --config=gcc41.cfg --action=build --tune=base sjeng
runspec --config=gcc41.cfg --action=build --tune=base GemsFDTD
runspec --config=gcc41.cfg --action=build --tune=base libquantum
runspec --config=gcc41.cfg --action=build --tune=base h264ref
runspec --config=gcc41.cfg --action=build --tune=base lbm
runspec --config=gcc41.cfg --action=build --tune=base omnetpp
runspec --config=gcc41.cfg --action=build --tune=base astar
runspec --config=gcc41.cfg --action=build --tune=base wrf
runspec --config=gcc41.cfg --action=build --tune=base sphinx
runspec --config=gcc41.cfg --action=build --tune=base xalancbmk
runspec --config=gcc41.cfg --action=build --tune=base specrand
